Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import app as application
  File "/home/patakk/foto/app.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import app as application
  File "/home/patakk/foto/app.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import app as application
  File "/home/patakk/foto/app.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/home/patakk/foto/passenger_wsgi.py", line 1, in <module>
    from app import application
  File "/home/patakk/foto/app.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
[2022-04-26 21:18:31,897] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][4012793] packetLen < 0
[2022-04-26 21:18:31,944] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][4012921] packetLen < 0
[2022-04-26 21:18:32,585] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][4012921] packetLen < 0
[2022-04-26 21:18:33,023] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][4012921] packetLen < 0
[2022-04-26 21:18:33,765] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][4012921] packetLen < 0
[2022-04-26 21:18:34,230] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][4012921] packetLen < 0
[2022-04-26 21:18:34,807] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][4012921] packetLen < 0
[2022-04-26 21:18:35,460] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][4012921] packetLen < 0
[2022-04-26 21:18:36,096] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][4012921] packetLen < 0
[2022-04-26 21:18:36,681] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][4012921] packetLen < 0
[2022-04-26 21:20:12,687] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:14,735] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:15,276] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:15,862] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:16,467] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:19,755] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:20,262] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:21,698] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:37,060] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:37,864] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:39,005] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:39,318] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:40,042] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:40,761] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:20:41,263] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:14,948] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:14,949] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:15,971] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:15,971] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:16,563] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:16,563] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:17,250] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:17,251] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:18,019] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:18,019] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:18,635] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:18,635] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:19,361] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:19,361] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:19,909] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:19,909] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:20,490] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:20,491] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:21,605] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:21,605] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:22,765] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:22,767] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:23,388] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:23,389] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:24,000] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:24,000] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:24,647] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:24,647] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:25,298] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:25,299] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:25,893] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:25,893] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:26,429] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:26,429] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:27,854] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:27,854] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:28,454] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:28,454] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:29,591] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:29,591] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:30,088] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:21:30,088] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:21,165] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:21,165] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:21,976] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:21,976] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:22,593] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:22,594] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:23,205] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:23,205] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:23,932] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:23,940] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:24,630] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:24,631] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:25,201] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:25,201] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:26,557] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:26,558] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:27,172] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:27,173] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:48,645] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:48,645] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:49,361] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:49,361] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:50,007] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:50,008] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:50,669] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:50,669] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:51,329] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:51,329] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:52,049] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:52,049] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:53,667] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:53,667] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:54,245] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:54,245] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:55,097] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:55,097] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:56,223] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:56,223] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:56,816] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:56,816] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:57,453] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:57,453] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:58,097] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:22:58,097] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:25,098] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:25,775] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:26,527] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:27,102] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:27,709] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:28,218] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:30,223] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:30,823] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:31,835] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:33,707] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:34,198] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:34,886] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:35,299] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:35,723] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:35,963] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:37,488] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:38,924] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:39,462] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:40,373] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:23:40,868] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[2022-04-26 21:26:59,044] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 16, in save_info
    #image = request.values['image']
TypeError: 'Request' object is not subscriptable
[UID:1814][956825] packetLen < 0
[UID:1814][956825] packetLen < 0
[UID:1814][960139] packetLen < 0
[UID:1814][960139] packetLen < 0
[UID:1814][960522] packetLen < 0
[UID:1814][960522] packetLen < 0
[UID:1814][960522] packetLen < 0
[UID:1814][960522] packetLen < 0
[UID:1814][960522] packetLen < 0
[UID:1814][960522] packetLen < 0
[UID:1814][960138] packetLen < 0
[UID:1814][962663] packetLen < 0
[UID:1814][962663] packetLen < 0
[UID:1814][962663] packetLen < 0
[UID:1814][962663] packetLen < 0
[UID:1814][962663] packetLen < 0
[UID:1814][962663] packetLen < 0
[UID:1814][962663] packetLen < 0
[2022-04-27 17:17:14,071] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    f.write(base64.decodebytes(image))
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:17:18,556] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    f.write(base64.decodebytes(image))
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:17:19,682] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    f.write(base64.decodebytes(image))
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:17:21,919] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    f.write(base64.decodebytes(image))
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:17:22,502] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    f.write(base64.decodebytes(image))
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:17:24,892] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    f.write(base64.decodebytes(image))
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:17:25,972] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    f.write(base64.decodebytes(image))
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:17:26,850] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    f.write(base64.decodebytes(image))
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:17:27,404] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    f.write(base64.decodebytes(image))
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:17:27,923] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    f.write(base64.decodebytes(image))
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:19,467] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:20,610] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:21,447] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:43,064] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:44,294] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:45,014] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:45,789] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:46,605] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:47,604] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:48,370] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[2022-04-27 17:19:49,068] ERROR in app: Exception on /save_info [POST]
Traceback (most recent call last):
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patakk/virtualenv/foto/3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/patakk/foto/app.py", line 18, in save_info
    imgstr = re.search(r'data:image/png;base64,(.*)',image_b64).group(1)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/opt/alt/python38/lib64/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
[UID:1814][972674] packetLen < 0
[UID:1814][972674] packetLen < 0
[UID:1814][972674] packetLen < 0
[UID:1814][973188] packetLen < 0
[UID:1814][973256] packetLen < 0
[UID:1814][974167] packetLen < 0
[UID:1814][974167] packetLen < 0
[UID:1814][974357] packetLen < 0
[UID:1814][974408] packetLen < 0
[UID:1814][974423] packetLen < 0
